### ISSUE TITLE
Error when sorting with no rows

### ISSUE THREAD

**Issue by drvic10k** [Sjeiti/TinySort#102]
Hi,
there's an error being thrown, when there are no rows to sort. In the console, you can see a warning "No elements to sort", but also an error "Uncaught TypeError: Cannot read property 'appendChild' of undefined"

you can see it here:
http://jsfiddle.net/46H6W/55/

**Comment by ctrl-f5** [comment]
I've also got this issue

**Comment by Sjeiti** [comment]
fixed for v2.2.4
