### ISSUE TITLE
in WHMCS Uncaught SyntaxError: Unexpected token ) 

### ISSUE THREAD

**Issue by spumo** [Sjeiti/TinySort#103]
Calling tinysort('ul#ulName>li', {data:'sortby'});
which is work perfectly in https://jsfiddle.net/.

but adding this to the WHMCS (script base) header.tpl 
<script type="text/javascript">
tinysort('ul#ulName>li', {data:'sortby'});
</script>

cause an error.

this is what php.index in WHMCS would see the code:
<script type="text/javascript">
tinysort('ul#ulName>li', );
</script>
+============+
, it seems it has a problem with {}, in tinysory (NodeList, {data:'foo'});
Thanks.
![uncaughterror](https://cloud.githubusercontent.com/assets/13505937/8893217/aaf04a6c-339d-11e5-8ec1-7376aba7dfce.png)

**Comment by Sjeiti** [comment]
Doesn't look like a Javascript issue to me; it seems that somehow apache/php serves an altered file where the object is stripped.
