### ISSUE TITLE
Sorting numbers with different locale settings

### ISSUE THREAD

**Issue by josmanperez** [Sjeiti/TinySort#106]
Hi!, I've been using the tinysort with no problem until now to sort tables with numbers. Now I'm using number_format function to provide easy readable values for numbers, due to the fact that I'm from Spain my number format will be:

2.004,23
1.025,45
and so on...

But with this format the tinysort function doesn't work as expected.... I've implemented different approaches but with no solution at all..

Can someone help me please

**Comment by Sjeiti** [comment]
I think the easiest would be to add a data- attribute to the element containing the 'proper' number value. For instance <li data-nr="2004.23">2.004,23</li>
