### ISSUE TITLE
How to sort nested div's like tables

### ISSUE THREAD

**Issue by ollie007** [Sjeiti/TinySort#107]
<div class=row><div class=name></div><div class=age></div></div>
    <div class=row><div class=name></div><div class=age></div></div>

and then order by age or name or both? by value in the div

**Comment by Sjeiti** [comment]
That would be something like (ordered by age first... then by name):
`tinysort(document.querySelectorAll('.row'),'.age','.name');`

**Comment by ollie007** [comment]
Hi, sorry but i am not getting this to work.....can you rearrange with the inner nested div's?

    <div class=row><div class=name><div class=age></div></div></div>
    <div class=row><div class=name><div class=age></div></div></div>

with a call, like this?
    tinysort(document.querySelectorAll('.row'),'.age');

Also how do i use the options?

    tinysort.defaults.order = 'desc';
