### ISSUE TITLE
Sorting rows of div's like table rows ??

### ISSUE THREAD

**Issue by ollie007** [Sjeiti/TinySort#108]
Hi, sorry but i am not getting this to work.....can you rearrange with the inner nested div's?

    <div class=row><div class=name><div class=age></div></div></div>
    <div class=row><div class=name><div class=age></div></div></div>
with a call, like this?
    tinysort(document.querySelectorAll('.row'),'.age');

Also how do i use the options?

    tinysort.defaults.order = 'desc';

PS. do i call the script in the header tag or can it be at the bottom of the page?

PPS. how do I sort them ONPAGELOAD?

**Comment by Sjeiti** [comment]
Here, check this: http://jsfiddle.net/Sjeiti/ewpL9uj0/

As for the options: read the dos: http://tinysort.sjeiti.com/#sorted-descending

Always add scripts to the bottom of the page, or better: lazy load them.
If you want to sort on a page load you simply add a load event listener to the document, or use the DOMContentLoaded event which fires slightly earlier.

**Comment by ollie007** [comment]
Ok you need to give me a hand with OnPageLoad, please give examples please

**Comment by Sjeiti** [comment]
document.addEventListener('load', function() {
        // do something
    }, false);
