### ISSUE TITLE
Put background color on result even tr (zebring the table rows)

### ISSUE THREAD

**Issue by bronson3** [Sjeiti/TinySort#109]
Hi every body
I want to to colorize background even tr before displaying result 
How can i script that ?
Any help would be appreciated 
Best rgds

**Comment by Sjeiti** [comment]
Use CSS 3 for that:

    tr:even { background-color: red; }

**Comment by bronson3** [comment]
Thanks for answering, i already use tr:even on initial table construction.
My question is : is there a way to trigger a callback on sorting finished or where can i add a loop for zebring the new row arrangement (i.e. if(index) is even ==> background color) inside tinySort script.
I am in trouble managing this ! 

Best rgds

**Comment by Sjeiti** [comment]
ah... I'm sorry, the correct syntax is

    tr:nth-child(even) { background-color: red; }

see here: http://jsfiddle.net/Sjeiti/mf4n4rgt/
