### ISSUE TITLE
åäö

### ISSUE THREAD

**Issue by BlackGears** [Sjeiti/TinySort#110]
Hello,

Without passing any extra arguments, tinysort will sort the Swedish characters (åäö) as äåö (note: the å should be before ä).

When adding the charOrder argument with 'åäö' as the rule it seems to make no difference.

Regards!

Update: [http://jsfiddle.net/eL9r1bqh/](http://jsfiddle.net/eL9r1bqh/)

**Comment by Sjeiti** [comment]
In your fiddle you have the property 'sortOrder' but in your comment you correctly describe 'charOrder'.  If I change it to 'charOrder' your fiddle works....
