### ISSUE TITLE
sort doesn't work after dynamic item insert 

### ISSUE THREAD

**Issue by ncou** [Sjeiti/TinySort#111]
Hi,

very nice plugin.
I have an issue with the sort. I inject a new element in my list (with a js script), and i want to sort the list.
But tinysort doesn't sort the new injected element.

Is there a workaround in my case ?

Thank you.

**Comment by Sjeiti** [comment]
Could you provide an example on jsfiddle? Normally this should not pose a problem (all examples on http://tinysort.sjeiti.com/ are js injected elements). So it could be something in your code.
