### ISSUE TITLE
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by creage** [Sjeiti/TinySort#113]
Trying to sort a collection of **detached** jQuery elements fails with the description above.

I believe, this part should be updated to respect such cases
`getComputedStyle(nodeList[0].parentNode,null)`

**Comment by Sjeiti** [comment]
Good point... with DocumentFragments and all.
Any ideas on ways to determine display===flex for detached elements? ...simply default to false? ...or optionally force it?
