### ISSUE TITLE
Add version history

### ISSUE THREAD

**Issue by alimony** [Sjeiti/TinySort#117]
I can't find any version history anywhere, so it's quite hard to determine what is new in each version, and whether I should update or not.

**Comment by Sjeiti** [comment]
Hmmm, I never really bothered because people could just look up the commit history. I don't intend to keep a separate file/list for version history but what I could do is elaborate the tags with release notes. Would that work for you?

**Comment by alimony** [comment]
That would be fantastic, thank you!

**Comment by Sjeiti** [comment]
I've added release notes to the tags up to a year back, that should be enough.

**Comment by alimony** [comment]
Very nice, I appreciate it.
