### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by EirikBirkeland** [Sjeiti/TinySort#118]
I would like an option to disable console.warn messages. While I was initially fond of the feedback, I'd prefer to be able to override console.warn with a custom logger passed in as an option, or perhaps just keeping the warning off by default.

I could suggest an implementation if interested.

**Comment by Sjeiti** [comment]
Good idea. The easiest implementation from the top of my head is an extra option called 'console' that is window.console by default, false if you want it turned off, or a custom object for anything other (so as long as it has a method 'warn').

**Comment by EirikBirkeland** [comment]
I added this in my fork, but now I realized that what I take issue with is that the error level seems a little high. I'd prefer if console.info was used instead of console.warn.

Perhaps a toggle to reduce the warning level would be an option? Or maybe I need to clean up my code, as I'm actually passing tinysort data before the dom is ready! :) Going to try adjusting a debounce.

**Comment by sergiorighi** [comment]
There should be an option to turn off console.warn messages.

**Comment by Sjeiti** [comment]
there is now
