### ISSUE TITLE
Toggle asc/desc with sub selector

### ISSUE THREAD

**Issue by eliluong** [Sjeiti/TinySort#120]
*sorry doubled submitted for some reason; ignore this one*

I have a layout as follows:
`<div id="main-container">
<div class="inner-container"><span class="sort-on-this">sorted text here</span></div>
<div class="inner-container"><span class="sort-on-this">sorted text here</span></div>
</div>`

And the code I used is this: 
`tinysort("div#main-container>div.inner-container", "span.sort-on-this", {order: 'desc'});`

It sorts ascending just fine. When I try to add the desc option, it doesn't seem to work. Is it incorrect? Thanks.

**Comment by Sjeiti** [comment]
use: tinysort("div#main-container>div.inner-container", {order: 'desc'});
