### ISSUE TITLE
Toggle asc/desc with sub selector

### ISSUE THREAD

**Issue by eliluong** [Sjeiti/TinySort#121]
I have a layout as follows:
`<div id="main-container"><div class="inner-container"><span class="sort-on-this">sorted text here</span></div><div class="inner-container"><span class="sort-on-this">sorted text here</span></div></div>`

And the code I used is this: 
`tinysort("div#main-container>div.inner-container", "span.sort-on-this", {order: 'desc'});`

It sorts ascending just fine. When I try to add the desc option, it doesn't seem to work. Is it incorrect? Thanks.

**Comment by Sjeiti** [comment]
You're doing it wrong. This means you're first sorting on 'div#main-container>div.inner-container' (asc) and when those are equal you proceed to sorting only 'span.sort-on-this'.
All you really need is: tinysort("div#main-container>div.inner-container", {order: 'desc'});
