### ISSUE TITLE
Is there a way to unsort? 

### ISSUE THREAD

**Issue by fifiteen82726** [Sjeiti/TinySort#125]
I am using this `TinySort` and feel amazing, but is there a approach to reset my list? 

My list was sorting on created time original. User can add, delete or edit list, then users can click sort button. Everything works fine, but how do I reset this list and include new data? Since I didn't store the new data (cause by adding, deleting or editing list), I just `append` that  to the bottom of the list and send `ajax` to backend to store them.

**Comment by Sjeiti** [comment]
Not out of the box no; Tinysort only sorts. But you could initialise adding a value for the original order and use that to sort to: https://jsfiddle.net/Sjeiti/66tgnwzg/

**Comment by fifiteen82726** [comment]
Thanks! I got it.

**Comment by abubelinha** [comment]
Thanks @Sjeiti for the jsfiddle example, but for some reason, it didn't work in my browser.
If I add a little modification now it works:
https://jsfiddle.net/abubelinha/t7dcjhak/
