### ISSUE TITLE
How to sort items per bootstrap rows?

### ISSUE THREAD

**Issue by claudchan** [Sjeiti/TinySort#128]
Hi,
I am looking for solutions, possible if TinySort can sort the items 3 items per row example?

```
<div class="row">
    <div class="col-sm-4"> item 1 </div>
    <div class="col-sm-4"> item 2 </div>
    <div class="col-sm-4"> item 3 </div>
</div>
<div class="row">
    <div class="col-sm-4"> item 4 </div>
    <div class="col-sm-4"> item 5 </div>
</div>
```

**Comment by Sjeiti** [comment]
I'm not entirely sure what you are trying to achieve. Have you read the documentation? There are plenty examples in there.
If you mean multiple rows within multiple parents then no. It would work if you just have one row parent.
