### ISSUE TITLE
sort in onLoad needs timeout

### ISSUE THREAD

**Issue by SabineMa** [Sjeiti/TinySort#130]
I do save the last sort order of my users. When he enters the page again, I want to sort the table initially. For this, I call tinysort in my onLoad function. It does not work. After trying around a while, I fount out, that when I add a timeout, it works: 

setTimeout(function(){  tinysort('#spf-gridTrips>div:not(.spf-table-header)',{selector:'a>.spf-grid-text-div>.spf-tab-trip-paymentSum',attr:'sortval',order:'desc'});  }, 50);

So my question: is this a bug? Is it not intended to work onLoad?

**Comment by Sjeiti** [comment]
Are you sure the load-event fires?
I did a quick test which works just fine (in Chrome because es6):
```
<!DOCTYPE html>
<html><body>
before load
<ul id="nr1">
    <li>4</li>
    <li>1</li>
    <li>3</li>
    <li>2</li>
</ul>
on load
<ul id="nr2">
    <li>4</li>
    <li>1</li>
    <li>3</li>
    <li>2</li>
</ul>
after load
<ul id="nr3">
    <li>4</li>
    <li>1</li>
    <li>3</li>
    <li>2</li>
</ul>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tinysort/2.3.6/tinysort.min.js"></script>
<script>
    const select = id => document.querySelectorAll(`#${id}>li`);
    tinysort(select('nr1'));
    window.addEventListener('load',()=>{
      tinysort(select('nr2'));
      setTimeout(tinysort.bind(tinysort, select('nr3')));
    })
</script>
</body></html>
```
