### ISSUE TITLE
Videos not auto playing on Chrome

### ISSUE THREAD

**Issue by Atyc** [Sjeiti/TinySort#131]
I am trying to sort a series of boxes. They contain images, text or videos.
On (document).ready all the boxes are sorted using TinySort.
For some reason, the videos will not autoplay after sorting on Chrome browser (or Canary). 
No errors or console logs appear and the boxes are correctly sorted.
Videos will autoplay if I disable the sorting.

EDIT: this seems to be a bug in Chrome:
When moving the element within the dom, the video pauses

**Comment by Sjeiti** [comment]
Ah,  you could do two things then: either check which video is playing before sorting and playing it after sorting. Or use flexbox order to sort: http://tinysort.sjeiti.com/#option-useFlex
