### ISSUE TITLE
Looks like sorting based on custom sort function not working

### ISSUE THREAD

**Issue by Manoj-Bisht** [Sjeiti/TinySort#132]
Hi,

I think the custom sort function not working. Pls look at the Demo page http://tinysort.sjeiti.com/#option-sortFunction. It is actually not performing any sorting there.

Thanks!

Manoj

**Comment by Sjeiti** [comment]
You're right, the example is not working. I'll have a look to check if the bug is in the example or the code.

**Comment by Manoj-Bisht** [comment]
Thanks Sjeiti..It looks like something broke in main code over period of time..I was exploring some examples over internet...where people are given solution of custom function..But even they are also not working..just as an example: http://jsfiddle.net/YQEZ4/.. though I found this on other places also

**Comment by Sjeiti** [comment]
Well, I checked and the method itself does work https://jsfiddle.net/Sjeiti/wkcayhq7/ (never wrote a unit test for this method, shame on me)
So it looks like it's just the example itself fails somewhere. I'll have a more thorough look later.

About the example fiddle you posted: you should be aware that [Array.prototype.sort](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) expects a numeral return value of either -1, 0 or 1

**Comment by Manoj-Bisht** [comment]
I checked your fiddle  https://jsfiddle.net/Sjeiti/wkcayhq7/
I played around with it, the data is already sorted in the example and when I changed the order, I did not get the desired output.
I think, I am missing something v basic here :(

**Comment by Sjeiti** [comment]
Hmbrlgh... something must have gone wrong setting the latest revision to the base version of the fiddle. Check again. Same fiddle is now working correctly...

**Comment by Manoj-Bisht** [comment]
Yes..It is working perfectly..Thanks a ton! Keep doing the great work :)

I got the other fiddle working by changing the reference to latest JS (taken from your example) and modifying the code to return -1,0 and 1.

There are many examples lying over stackover flow for this custom sort which are not working...reason I can say is 1) referring to old tinysort.min.js 2) using different version of jquery.tinysort.min.js, tinysort.charorder.js

**Comment by abubelinha** [comment]
Actually, the main question remains ...
If the jsfiddle implementation works, why the example in TinySort webpage is faling?
I got exactly the same problem: I have implemented a slightly modified version of this fsfiddle so I can solve the problem I just reported in https://github.com/Sjeiti/TinySort/issues/143

And I solved it: https://jsfiddle.net/abubelinha/gtyexo5m/
But despite my example jsfiddle is working, when I try to call the funcion in my webpage it does not work.  Whenever I introduce the sortFunction parameter, it fails:

tinysort( ... , {sortFunction: myPreviouslyDefinedFunction});

tinysort( ... , {sortFunction: function(a,b) { ... my sorting code ... } });

Both ways of inserting that call in my webpage, do raise an "Uncaught SyntaxError: Unexpected token }"

**Comment by Sjeiti** [comment]
Yeahyeah, still haven't fixed it, I'm sorry... it's not very high on my todo list so pull requests are welcome. 

But `unexpected token }` looks like it's simply an error in your code. What kind of IDE are you using, doesn't it pick up on syntax?

**Comment by abubelinha** [comment]
Thanks for your answer. 
Sorry, I am not good on catching errors. It is just the information returned in Google Chrome developer console.  that message I was really not sure about this being an error in your library or in my code.
But as the example in your page was also failing, I thought both problems could be related.

My page code is a bit overcomplicated and runs in a LAN. I will try to reproduce the error in a public site if I can.
