### ISSUE TITLE
Suggestion Only

### ISSUE THREAD

**Issue by satheeshkrishna** [Sjeiti/TinySort#135]
Can we expect the JS library available in NuGet? We are expecting this for Asp.Net MVC 5 project.

**Comment by Sjeiti** [comment]
I'd be willing to make it so but I have little experience with .net and none with nuget. I could follow [this list](https://docs.microsoft.com/en-gb/nuget/create-packages/creating-a-package) blindly but I'd probably have no idea what I was doing, nor could I properly test it. It might be better and faster if you'd do it and send a pull request.

**Comment by tetsuo13** [comment]
We've been using this library as an internal NuGet package for a little while. I've created pull request #138 where I've added a NUSPEC file for the latest, non-jQuery version. I can upload to NuGet.org if that's OK.

**Comment by Sjeiti** [comment]
I've merged it. You're welcome to upload to NuGet.org
Does NuGet require a tag? (like npm does)

**Comment by tetsuo13** [comment]
NuGet doesn't integrate as closely -- or at all -- with the repo as npm does. Instead, the package is generated using `nuget.exe` with the details from the NUSPEC file.

For version 2.3.6 the file is ready to go as I've copied the relevant info needed. When the next release is made and a new package needs to be generated, the NUSPEC file will need to updated beforehand by updating the contents in the `version` tag -- and ideally the `releaseNotes` tag as well but that tag isn't required.

**Comment by tetsuo13** [comment]
I've added the package to NuGet.org:

https://www.nuget.org/packages/tinysort/

@satheeshkrishna I've gone as far back as version 2.2.6 but can go further if you need something before that version.
