### ISSUE TITLE
More cyrillic letters

### ISSUE THREAD

**Issue by igoradamenko** [Sjeiti/TinySort#136]
> Cyri**ll**ic
> since only one of these is my native language please feel free to contact me if you think corrections are in order

Hello!
In Russian (Cyrillic language) we also have letters 'ё', 'й', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я'. I want to add them to readme, but don't sure, should I extend Cyrillic set or add Russian set separately?

**Comment by Sjeiti** [comment]
Hi, sorry for the delay. I think adding them as Russian would be better. I don't know how many languages have Cyrillic letters but they are bound to differ.

**Comment by igoradamenko** [comment]
Okay, I've created #137.

**Comment by Sjeiti** [comment]
cool, thank you
