### ISSUE TITLE
Absent attribute

### ISSUE THREAD

**Issue by Rourke101** [Sjeiti/TinySort#139]
When the attribute is absent, the sorting does not work on the element.

I would expect
`    <p>....`

To behave in the same way as
`    <p sortable="">....`

at least for the emptyEnd feature

(moreover, if in the list there is an element without the sorting attribute, the sorting gives an incorrect result)

**Comment by Sjeiti** [comment]
That depends on your call really: wheter you're sorting `tsort('p')` or tsort('[sortable]').
For instance: document.querySelector('[sortable]') will include the paragraph with the empty attribute. An empty attribute is definitely not the same as a missing attribute (ie disabled or readonly attributes on input elements).

But you are right that there is something off here: https://jsfiddle.net/Sjeiti/awq13yda/
It might have somthing todo with HTMLElement.getAttribute('missingAttr') yielding null...

**Comment by Rourke101** [comment]
The actual call I am making is:

**Comment by Sjeiti** [comment]
This should be fixed for v3.2.2 which differentiates better between empty and absent attributes.
