### ISSUE TITLE
Sort without Decimal?

### ISSUE THREAD

**Issue by jasonjflaherty** [Sjeiti/TinySort#142]
I've been working on a project that has a list like so:

- 1
- 1.1
- 1.2
- 1.10
- 1.11

where 1.10 > 1.2

Allowing a sort disregarding a decimal would be a nice option.

**Comment by Sjeiti** [comment]
I am not sure I follow the logic here. Can you elaborate?

**Comment by jasonjflaherty** [comment]
I could be missing it, but I don't see how I can make tinysort sort can make sure that 1.10 is larger than 1.9 for example. I was thinking if we removed the decimal, 110 would be bigger than 19... I am not sure that is the best solution here... just a thought. thanks for the reply!

**Comment by Sjeiti** [comment]
Ah right... so you do not want to treat 1.10 and 1.9  as floating point numbers but as a dot-separated array of numbers (as in version numbering).

Tinysort would work this way if the sorted value is not recognized as a number. You could force this behaviour like so: create an attribute with the same value but replace the dot with a hyphen (for instance): `Array.from(document.querySelector('li')).forEach(li=>li.setAttribute('value',li.textContent.replace(/\./g,'-')))`
Then you can just: `tsort('#somelist>li',{attr:'value'})`

here's a fiddle: http://jsfiddle.net/Sjeiti/wx5oL027/

**Comment by jasonjflaherty** [comment]
Thanks again @Sjeiti for the answer there.
