### ISSUE TITLE
Internet Explorer Element doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by JNBG** [Sjeiti/TinySort#150]
Hi there,
found a bug - on IE 10 (didn't dare to go lower) I get the above mentioned error when trying to sort a list of divs. Here is my Code I use to the plugin:

tinysort('.listing-item', {
     selector: '.' + selectorString,
     attr: 'data-' + selectorString
}, {selector: '.sort-date', attr: 'data-sort-date'});

selectorString is just a string working as class selector. It should sort the list by the selector and then subsort it by date. Works fine on all modern browsers except IE

[This](https://stackoverflow.com/questions/35215360/getting-error-object-doesnt-support-property-or-method-assign) might be a possible solution

**Comment by Sjeiti** [comment]
IE 10 is not supported by this plugin. If people support IE 10 there's enough polyfills that they should `npm install` anyway. This plugin is not the proper place for it.

**Comment by dimative** [comment]
Hello. This plugin does not work IE10. Can you offer me any solution for IE10?

**Comment by Sjeiti** [comment]
Yes the solution is using the proper polyfills... for instance `npm i -S object-assign`.
