### ISSUE TITLE
Wrong sorting of numbers after a minus

### ISSUE THREAD

**Issue by springerarthur** [Sjeiti/TinySort#151]
Hi, there is a strange bug in the TinySort library.

When I have a number after a minus at the end of a text, it is sorted in the wrong direction. When there is any letter after the number, it works as expected.

The issue is reproduced in this fiddle: [http://jsfiddle.net/gcLhon04/4/](http://jsfiddle.net/gcLhon04/4/)

**Comment by Sjeiti** [comment]
It's not a bug it's a feature :-D
It's intended behaviour. It will read numeral values including minus signs (negative) unless you specify {ignoreDashes:true} .
