### ISSUE TITLE
How would I import this in a chrome extension?

### ISSUE THREAD

**Issue by alexbfree** [Sjeiti/TinySort#152]
Hi, the instructions tell me how to install this using npm, but I need to get it working in a chrome extension..
I tried adding `tinysort.js` to my `manifest.json`, 
and then
```
import(chrome.extension.getURL('tinysort.js')).then(tinysort => tinysort(document.querySelectorAll('div.nodesThatNeedSorting'));
```
but I get an error that tinysort is not defined. Any advice how to import this function in a standalone javascript file? I see it returns a Promise but can't figure out how to use the result to get at the function....

Thanks!

**Comment by Sjeiti** [comment]
I have little experience with Chrome extentions. Can't you just bundle it with Webpack or something?
