### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Glen-Dango** [Sjeiti/TinySort#155]
cant work out from the docs which cdn i need???

**Comment by Sjeiti** [comment]
I don't understand what the problem is, it's right there on tinysort.sjeiti.com and it's the first result when you google 'tinysort cdn'.

**Comment by Sjeiti** [comment]
The cdn url is https://cdnjs.com/libraries/tinysort
which means you'll probably only need https://cdnjs.cloudflare.com/ajax/libs/tinysort/3.2.5/tinysort.min.js

http://tinysort.sjeiti.com should provide you with enough examples but if you want html as wel I suggest you look at the source or search on jsfiddle: 0i71j35i304i39j30i10.DLCNiPZQXqs

**Comment by Glen-Dango** [comment]
great i got it working. not sure how you connect the sort and reset button
up to the sort function so will take a while trying to work that out.
 thanks for reply though .
