### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Glen-Dango** [Sjeiti/TinySort#156]
Can i use this in a loop with php elements? I'am trying to sort by <p1> i.e. the price..   
 ive got this plugin working with basic lists of numbers and text with tinysort('div#xmix>p1');  

 but cant seem to get it to catch the <p1> element in this example where i have dynamic code and many products. 

<div> container 
loop code ////

  <div class="card-body ">
    <h5  class="title"><b> <?=$elements->advert_heading ?></b></h5>
     <p1 class="price"><b><?= $elements->price_text ?></b></p1>
    <p class="card-text"><?= $elements->bullet1 ?></p>
    <p class="card-text"><?= $elements->bullet2 ?></p>
    <a href="#" class="btn btn-secondary">Full Details</a>

**Comment by Glen-Dango** [comment]
gits stripped all my example code...hope it makes sense

**Comment by Glen-Dango** [comment]
jeez,,git stripped all code and no i cant see delete anywhere to delete the comment... wow

**Comment by Glen-Dango** [comment]
i cant delete the question,,, git stripped code and now i cant delete... 
\

**Comment by Sjeiti** [comment]
ps: this is an issue tracker, not a q&a forum: use Stackoverflow for that.
