### ISSUE TITLE
Is it possible to sort from the second character?

### ISSUE THREAD

**Issue by MrzAOK** [Sjeiti/TinySort#167]
Hi, is it possible to sort starting from the 2nd letter or character in a list? For example, I want to ignore the letters in bold below:

- **Y**Bat
- **A**Dog
- **Z**Apple

so the correct working order would be:

- **Z**Apple
- **Y**Bat
- **A**Dog

**Comment by Sjeiti** [comment]
You can [sort by data attribute](http://tinysort.sjeiti.com/#sorted-by-attribute-value) if you write your elements like this: `<li data-sort="bat">YBat</li>`.

Or you could use [a custom sort function](http://tinysort.sjeiti.com/#custom-sort-function).

**Comment by MrzAOK** [comment]
What about if I don't have access to edit the markup? Currently I'm hiding the first letter with CSS, but I'd still like it to sort.

**Comment by Sjeiti** [comment]
Your only option is a custom sort function then. But if you're going to do that for all your sorts you might as well ditch TinySort and just write it yourself. It's not that hard: https://codesandbox.io/s/simplevanillaasc-decsort-6jihj
