### ISSUE TITLE
Automatic sort order

### ISSUE THREAD

**Issue by Dr-Ash** [Sjeiti/TinySort#182]
Hello,

I think a very useful functionality for tinySort would be another order value ex: `auto`, that detects automatically order direction (store it somewhere, and reverts it ?)

**Comment by Sjeiti** [comment]
Hi,

I'm afraid the complexity of trying to detect the sort order could easily double the current filesize.

The order in the following list could be anything, and it is only three entries:

```html
<ul>
  <li value="1">á</li>
  <li><span>b<span></li>
  <li data-order="2">d<span>c<span></li>
<ul>
```

I'd be willing to checkout an idea or pull-request though.
