### ISSUE TITLE
IE8 Support

### ISSUE THREAD

**Issue by FlashJunior** [Sjeiti/TinySort#91]
I needed Version 2.1.1 working in IE8.

If somebody need it also; add this to your JS:

```javascript
if (!('forEach' in Array.prototype)) {
	Array.prototype.forEach= function(action, that) {
		for (var i= 0, n= this.length; i<n; i++){
			if (i in this){
				action.call(that, this[i], i, this);
			}
		}
	};
}

if (!('map' in Array.prototype)) {
	Array.prototype.map= function(mapper, that) {
		var other= new Array(this.length);
		for (var i= 0, n= this.length; i<n; i++){
			if (i in this){
				other[i]= mapper.call(that, this[i], i, this);
			}
		}
		return other;
	};
}
```

**Comment by Sjeiti** [comment]
That is a good minimal solution. But when working with IE8 I find it generally easier to add the entire [es5-shim](https://github.com/es-shims/es5-shim) in a conditional comment.

**Comment by FlashJunior** [comment]
thx for the hint!

I needed it for a small Project. So i decided not to add an other script for "ie polyfill" who is 4kb (4times bigger than the sort script :-))
