### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by fabrz** [Sjeiti/TinySort#93]
Hi,

Just noticed an error when loading the library. Do you know what could be the problem? This happens when I load the page, the plugin has not been initialized yet. I'm gonna attach you some lines of code where the error happens.

				// using lowerCase instead of upperCase so _ will sort before
				for (var i=32,s=frCrCd(i),len=255;i<len;i++,s=frCrCd(i).toLowerCase()) {
					if (fnIndexOf.call(a,s)===-1) a.push(s); 
				}
				return a.sort();

Line 37 of TinySort Charorder library.

Many Thanks

**Comment by Sjeiti** [comment]
It looks as though the plugin is initialised before tinysort (since 'fnIndexOf' is undefined). You might have switched the load order of the .js files. Incidentally, in my current (unpushed) version this variable is set within the plugin itself.
