### ISSUE TITLE
Possible to Toggle Ascending/Descending?

### ISSUE THREAD

**Issue by nicholasalanbrown** [Sjeiti/TinySort#96]
This seems like a common implementation. How would I toggle the order from ascending to descending and back on click via jQuery?

**Comment by Sjeiti** [comment]
Did you read this? :: http://tinysort.sjeiti.com/#sorted-descending
Toggle a boolean on click and use it with a ternary operator

    isAsc = true;
    function handleClickEvent(){
        tinysort(Nodelist,{order:(isAsc=!isAsc)?'asc':'desc'});
    }

I'll leave the jQuery implementation to your own imagination...

**Comment by nicholasalanbrown** [comment]
I'm actually not able to get this to work. The sort responds to the true/false value of isAsc, but it doesn't toggle the value when tinysort executes. Here's my code (I'm using Meteor):

```
Template.home.rendered = function() {
	isAsc = true;
};

Template.home.events({
    'click #deckSorter': function() {
    	tinysort('#deckList>.deck',{data: 'deck', order:(isAsc=!isAsc)?'asc':'desc'});
	}
});
```

Any ideas?

**Comment by Sjeiti** [comment]
Here's a fiddle: http://jsfiddle.net/Sjeiti/yhxshfh4/

I don't know anything about Meteor but the code you pasted looks a little off: is that an implied global in that first function definition?... or does Meteor handle that?

What does querySelectorAll return for '#deckList>.deck'? (you should cache that into a NodeList, unless the contents changes a lot)

Does a console log in the event handler return a toggling boolean for isAsc?

**Comment by Sjeiti** [comment]
ps: the fiddle uses the function scope of the event handler for the boolean (might be an easier solution)... that should work just as well as long as you don't change the scope (bind, call, apply).

**Comment by nicholasalanbrown** [comment]
Nevermind, I'm an idiot. I had included the div id twice in my html, once on the li and again on the a. I've been at this for hours - ridiculous. Works like a charm now.

Out of curiosity what's the benefit of caching the DOM selector in a NodeList? The content doesn't change often...

**Comment by Sjeiti** [comment]
Haha... oh the fun of programming :-p

The benefit of caching is speed (trading computation for memory). Granted, the speed increase in this case is minimal. But there is a noticable difference in never caching any DOM nodes and always caching DOM nodes (especially for jQuery selectors).

**Comment by nicholasalanbrown** [comment]
Ah. So you're saying select the DOM element via JQuery and then set it
equal to NodeList, and then use the NodeList variable in the TinySort
function?

**Comment by Sjeiti** [comment]
No, I was talking about node selection in general. Instead of doing `$('#asdf>li')` several times through your script you're better off doing var `$asdfLi = $('#asdf').find('>li');` just once and use that variable.
