### ISSUE TITLE
charOrder problem

### ISSUE THREAD

**Issue by Emp3r** [Sjeiti/TinySort#99]
Hi, 
I need to sort table by Czech alphabet. I tried example from the website but it didn't sort well. Chars *'ěščřž'* are always after *'z'* and thats wrong. 

I also tried to write my own charOrder but it has the same issue.
My complete char order should look like this:
``` 
charOrder:'a[á]bcčdďeéěfgh{ch}i[í]jklmnňo[ó]pqrřsštťuůúvwxy[ý]zž'
 ```

And the whole tiny sort call like this:
 ```
tinysort(
    tableBody.querySelectorAll('tr'),
    {
        selector:'td:nth-child('+(tableHeaderIndex+1)+')',
        charOrder:'aábcčdďeéěfgh{ch}iíjklmnňoópqrřsštťuůúvwxyýzž', 
        order: order
    }
);
 ```

Thanks for any help.

**Comment by Sjeiti** [comment]
Could you provide a jsfiddle like [this one](http://jsfiddle.net/Sjeiti/d7k9hgyb/). So I have some good data to test against.

**Comment by Emp3r** [comment]
My bad, It works fine on jsfiddle even with the same data I used in my project, but on the projects website it doesn't. I tried to copy everything into the fiddle, but it still works there. The problem is obviously not on TinySort side.
